export const MONTHS = [
  { id: 1, month: "January", value: "1" },
  { id: 2, month: "February", value: "2" },
  { id: 3, month: "March", value: "3" },
  { id: 4, month: "April", value: "4" },
  { id: 5, month: "May", value: "5" },
  { id: 6, month: "June", value: "6" },
  { id: 7, month: "July", value: "7" },
  { id: 8, month: "August", value: "8" },
  { id: 9, month: "September", value: "9" },
  { id: 10, month: "October", value: "10" },
  { id: 11, month: "November", value: "11" },
  { id: 12, month: "December", value: "12" },
];

export const STATES = [
  "India",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];

export const YEARS = [
  // {
  //     label: "2023-24",
  //     value: "2023",
  // },
  {
    label: "2022-23",
    value: "2022",
  },
  {
    label: "2021-22",
    value: "2021",
  },
  {
    label: "2020-21",
    value: "2020",
  },
  {
    label: "2019-20",
    value: "2019",
  },
];

export const QUARTERS = [
  {
    label: "Quarter-1",
    value: "1",
  },
  {
    label: "Quarter-2",
    value: "2",
  },
  {
    label: "Quarter-3",
    value: "3",
  },
  {
    label: "Quarter-4",
    value: "4",
  },
];

export const DATA_NAMES = [
  {
    key: "months6_59IfaPercentO",
    value:
      "Percentage of children 6-59 months provided 8-10 doses (1ml) of Iron and Folic Acid (IFA) syrup",
  },
  {
    key: "pregWomenIfaPercentC",
    value:
      "Percentage of pregnant women (PW) given 180 Iron and Folic Acid (IFA) tablets",
  },
  {
    key: "motherIfaPercentF",
    value: "Percentage of mothers given Iron and Folic Acid (IFA) tablets",
  },
  {
    key: "adols10_15IfaPercentH",
    value:
      "Percentage of Adolescents (6-12 class) provided 4 Iron and Folic Acid (IFA) tablets in schools",
  },
  {
    key: "years6_9IfaPercentP",
    value:
      "Percentage of children covered under WIFS JUNIOR (5-9 years) provided 4-5 iron and folic acid (IFA) tablets (In schools + out of school)",
  },
];

export const MAP_DATA = [
  {
    id: 1,
    code: "IND",
    name: "INDIA",
    mapName: "India",
  },
  {
    id: 2,
    code: "IND035",
    name: "ANDAMAN AND NICOBAR ISLANDS",
    codeMap: "IN-AN",
    mapName: "Andaman & Nicobar Island",
  },
  {
    id: 6,
    code: "IND028",
    name: "ANDHRA PRADESH",
    codeMap: "IN-AP",
    mapName: "Andhra Pradesh",
  },
  {
    id: 33,
    code: "IND012",
    name: "ARUNACHAL PRADESH",
    codeMap: "IN-AR",
    mapName: "Arunachal Pradesh",
  },
  {
    id: 59,
    code: "IND018",
    name: "ASSAM",
    codeMap: "IN-AS",
    mapName: "Assam",
  },
  {
    id: 95,
    code: "IND010",
    name: "BIHAR",
    codeMap: "IN-BR",
    mapName: "Bihar",
  },
  {
    id: 134,
    code: "IND004",
    name: "CHANDIGARH",
    codeMap: "IN-CH",
    mapName: "Chandigarh",
  },
  {
    id: 136,
    code: "IND022",
    name: "CHHATTISGARH",
    codeMap: "IN-CT",
    mapName: "Chhattisgarh",
  },
  {
    id: 165,
    code: "IND038",
    name: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    codeMap: "IN-DN",
    mapName: "Dadara & Nagar Haveli",
  },
  {
    id: 1999,
    code: "IND038",
    name: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    codeMap: "IN-DD",
    mapName: "Daman & Diu",
  },

  {
    id: 169,
    code: "IND007",
    name: "DELHI",
    codeMap: "IN-DL",
    mapName: "Delhi",
  },
  {
    id: 181,
    code: "IND030",
    name: "GOA",
    codeMap: "IN-GA",
    mapName: "Goa",
  },
  {
    id: 184,
    code: "IND024",
    name: "GUJARAT",
    codeMap: "IN-GJ",
    mapName: "Gujarat",
  },
  {
    id: 218,
    code: "IND006",
    name: "HARYANA",
    codeMap: "IN-HR",
    mapName: "Haryana",
  },
  {
    id: 241,
    code: "IND002",
    name: "HIMACHAL PRADESH",
    codeMap: "IN-HP",
    mapName: "Himachal Pradesh",
  },
  {
    id: 254,
    code: "IND001",
    name: "JAMMU AND KASHMIR",
    codeMap: "IN-JK",
    mapName: "Jammu & Kashmir",
  },
  {
    id: 275,
    code: "IND020",
    name: "JHARKHAND",
    codeMap: "IN-JH",
    mapName: "Jharkhand",
  },
  {
    id: 300,
    code: "IND029",
    name: "KARNATAKA",
    codeMap: "IN-KA",
    mapName: "Karnataka",
  },
  {
    id: 332,
    code: "IND032",
    name: "KERALA",
    codeMap: "IN-KL",
    mapName: "Kerala",
  },
  {
    id: 347,
    code: "IND037",
    name: "LADAKH",
    codeMap: "IN-LA",
    mapName: "Ladakh",
  },
  {
    id: 350,
    code: "IND031",
    name: "LAKSHADWEEP DISTRICT",
    codeMap: "IN-LD",
    mapName: "Lakshadweep",
  },
  {
    id: 352,
    code: "IND023",
    name: "MADHYA PRADESH",
    codeMap: "IN-MP",
    mapName: "Madhya Pradesh",
  },
  {
    id: 405,
    code: "IND027",
    name: "MAHARASHTRA",
    codeMap: "IN-MH",
    mapName: "Maharashtra",
  },
  {
    id: 442,
    code: "IND014",
    name: "MANIPUR",
    codeMap: "IN-MN",
    mapName: "Manipur",
  },
  {
    id: 459,
    code: "IND017",
    name: "MEGHALAYA",
    codeMap: "IN-ML",
    mapName: "Meghalaya",
  },
  {
    id: 472,
    code: "IND015",
    name: "MIZORAM",
    codeMap: "IN-MZ",
    mapName: "Mizoram",
  },
  {
    id: 484,
    code: "IND013",
    name: "NAGALAND",
    codeMap: "IN-NL",
    mapName: "Nagaland",
  },
  {
    id: 498,
    code: "IND021",
    name: "ODISHA",
    codeMap: "IN-OR",
    mapName: "Odisha",
  },
  {
    id: 529,
    code: "IND034",
    name: "PUDUCHERRY",
    codeMap: "IN-PY",
    mapName: "Puducherry",
  },
  {
    id: 534,
    code: "IND003",
    name: "PUNJAB",
    codeMap: "IN-PB",
    mapName: "Punjab",
  },
  {
    id: 558,
    code: "IND008",
    name: "RAJASTHAN",
    codeMap: "IN-RJ",
    mapName: "Rajasthan",
  },
  {
    id: 592,
    code: "IND011",
    name: "SIKKIM",
    codeMap: "IN-SK",
    mapName: "Sikkim",
  },
  {
    id: 599,
    code: "IND033",
    name: "TAMIL NADU",
    codeMap: "IN-TN",
    mapName: "Tamil Nadu",
  },
  {
    id: 638,
    code: "IND036",
    name: "TELANGANA",
    mapName: "Telangana",
  },
  {
    id: 672,
    code: "IND016",
    name: "TRIPURA",
    codeMap: "IN-TR",
    mapName: "Tripura",
  },
  {
    id: 681,
    code: "IND009",
    name: "UTTAR PRADESH",
    codeMap: "IN-UP",
    mapName: "Uttar Pradesh",
  },
  {
    id: 757,
    code: "IND005",
    name: "UTTARAKHAND",
    codeMap: "IN-UT",
    mapName: "Uttarakhand",
  },
  {
    id: 771,
    code: "IND019",
    name: "WEST BENGAL",
    codeMap: "IN-WB",
    mapName: "West Bengal",
  },
];

const MAP_STATES = [
  "Andaman & Nicobar Island",
  "Andhra Pradesh",
  "Assam",
  "Arunanchal Pradesh",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadara & Nagar Haveli",
  "Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  // "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const map_data = [
  ["madhya pradesh", 0],
  ["uttar pradesh", 0],
  ["karnataka", 0],
  ["nagaland", 0],
  ["bihar", 0],
  ["lakshadweep", 0],
  ["andaman and nicobar", 0],
  ["assam", 0],
  ["west bengal", 0],
  ["puducherry", 0],
  ["daman and diu", 0],
  ["gujarat", 0],
  ["rajasthan", 0],
  ["dadara and nagar havelli", 0],
  ["chhattisgarh", 0],
  ["tamil nadu", 0],
  ["chandigarh", 0],
  ["punjab", 0],
  ["haryana", 0],
  ["andhra pradesh", 0],
  ["maharashtra", 0],
  ["himachal pradesh", 0],
  ["meghalaya", 0],
  ["kerala", 0],
  ["telangana", 0],
  ["mizoram", 35],
  ["tripura", 0],
  ["manipur", 0],
  ["arunanchal pradesh", 0],
  ["jharkhand", 0],
  ["goa", 0],
  ["nct of delhi", 0],
  ["odisha", 0],
  ["jammu and kashmir", 0],
  ["sikkim", 0],
  ["uttarakhand", 0],
];
